class DefaultWordFrequencyLists:

    default_wf_lists = {
        'en': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_english.csv',
        'es': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_spanish.csv',
        'fr': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_french.csv',
        'de': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_german.csv',
        'it': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_italian.csv',
        'ru': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_russian.csv',
        'zh': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_chinese_simplified.csv',
        'af' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/af/af_full.txt",
        'ar' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ar/ar_full.txt",
        'bg' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/bg/bg_full.txt",
        'bn' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/bn/bn_full.txt",
        'br' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/br/br_full.txt",
        'bs' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/bs/bs_full.txt",
        'ca' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ca/ca_full.txt",
        'cs' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/cs/cs_full.txt",
        'da' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/da/da_full.txt",
        'el' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/el/el_full.txt",
        'eo' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/eo/eo_full.txt",
        'et' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/et/et_full.txt",
        'eu' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/eu/eu_full.txt",
        'fa' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fa/fa_full.txt",
        'fi' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fi/fi_full.txt",
        'gl' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/gl/gl_full.txt",
        'he' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/he/he_full.txt",
        'hi' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/hi/hi_full.txt",
        'hr' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/hr/hr_full.txt",
        'hu' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/hu/hu_full.txt",
        'hy' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/hy/hy_full.txt",
        'id' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/id/id_full.txt",
        'is' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/is/is_full.txt",
        'ja' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ja/ja_full.txt",
        'ka' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ka/ka_full.txt",
        'kk' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/kk/kk_full.txt",
        'ko' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ko/ko_full.txt",
        'lt' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/lt/lt_full.txt",
        'lv' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/lv/lv_full.txt",
        'mk' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/mk/mk_full.txt",
        'ml' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ml/ml_full.txt",
        'ms' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ms/ms_full.txt",
        'nl' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/nl/nl_full.txt",
        'no' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/no/no_full.txt",
        'pl' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/pl/pl_full.txt",
        'pt' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/pt/pt_full.txt",
        'pt_br' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/pt_br/pt_br_full.txt",
        'ro' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ro/ro_full.txt",
        'si' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/si/si_full.txt",
        'sk' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sk/sk_full.txt",
        'sl' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sl/sl_full.txt",
        'sq' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sq/sq_full.txt",
        'sr' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sr/sr_full.txt",
        'sv' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sv/sv_full.txt",
        'ta' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ta/ta_full.txt",
        'te' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/te/te_full.txt",
        'th' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/th/th_50k.txt",
        'tl' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/tl/tl_full.txt",
        'tr' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/tr/tr_full.txt",
        'uk' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/uk/uk_full.txt",
        'ur' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ur/ur_full.txt",
        'vi' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/vi/vi_full.txt",
        'ze_en' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ze_en/ze_en_full.txt",
        'ze_zh' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ze_zh/ze_zh_full.txt",
        'zh_cn' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/zh_cn/zh_cn_full.txt",
        'zh_tw' : "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/zh_tw/zh_tw_full.txt",
    }