from collections import defaultdict

# https://github.com/orgtre/google-books-ngram-frequency

GOOGLE_BOOKS_SOURCES = {
    'en': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_english.csv',
    'es': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_spanish.csv',
    'fr': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_french.csv',
    'de': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_german.csv',
    'it': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_italian.csv',
    'ru': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_russian.csv',
    'zh': 'https://raw.githubusercontent.com/orgtre/google-books-ngram-frequency/main/ngrams/1grams_chinese_simplified.csv',
}

# https://github.com/orgtre/top-open-subtitles-sentences (excluding Chinese, as they appear to contain only characters?)
# https://github.com/hermitdave/FrequencyWords

TOP_OPEN_SUBTITLES_SENTENCES_SOURCES = {
    'en': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/en_top_words.csv',
    'es': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/es_top_words.csv',
    'fr': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/fr_top_words.csv',
    'de': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/de_top_words.csv',
    'it': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/it_top_words.csv',
    'ru': 'https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ru_top_words.csv',
    'af': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/af_top_words.csv",
    'ar': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ar_top_words.csv",
    'bg': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/bg_top_words.csv",
    'bn': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/bn_top_words.csv",
    'br': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/br_top_words.csv",
    'bs': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/bs_top_words.csv",
    'ca': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ca_top_words.csv",
    'cs': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/cs_top_words.csv",
    'da': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/da_top_words.csv",
    'el': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/el_top_words.csv",
    'eo': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/eo_top_words.csv",
    'et': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/et_top_words.csv",
    'eu': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/eu_top_words.csv",
    'fa': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/fa_top_words.csv",
    'fi': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/fi_top_words.csv",
    'gl': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/gl_top_words.csv",
    'he': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/he_top_words.csv",
    'hi': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/hi_top_words.csv",
    'hr': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/hr_top_words.csv",
    'hu': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/hu_top_words.csv",
    'hy': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/hy_top_words.csv",
    'id': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/id_top_words.csv",
    'is': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/is_top_words.csv",
    'ja': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ja_top_words.csv",
    'ka': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ka_top_words.csv",
    'kk': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/kk_top_words.csv",
    'ko': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ko_top_words.csv",
    'lt': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/lt_top_words.csv",
    'lv': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/lv_top_words.csv",
    'mk': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/mk_top_words.csv",
    'ml': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ml_top_words.csv",
    'ms': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ms_top_words.csv",
    'nl': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/nl_top_words.csv",
    'no': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/no_top_words.csv",
    'pl': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/pl_top_words.csv",
    'pt': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/pt_top_words.csv",
    'pt_br': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/pt_br_top_words.csv",
    'ro': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ro_top_words.csv",
    'si': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/si_top_words.csv",
    'sk': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/sk_top_words.csv",
    'sl': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/sl_top_words.csv",
    'sq': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/sq_top_words.csv",
    'sr': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/sr_top_words.csv",
    'sv': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/sv_top_words.csv",
    'ta': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ta_top_words.csv",
    'te': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/te_top_words.csv",
    'th': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/th_top_words.csv",
    'tl': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/tl_top_words.csv",
    'tr': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/tr_top_words.csv",
    'uk': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/uk_top_words.csv",
    'ur': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/ur_top_words.csv",
    'vi': "https://raw.githubusercontent.com/orgtre/top-open-subtitles-sentences/refs/heads/main/bld/top_words/vi_top_words.csv",
    'zh': 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/zh_cn/zh_cn_full.txt',
    'zh_tw': "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/zh_tw/zh_tw_full.txt",
    'ze_en': "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ze_en/ze_en_full.txt",
    'ze_zh': "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ze_zh/ze_zh_full.txt",
}


def get_default_wf_list_sources() -> dict[str, list[str]]:

    combined = defaultdict(list)

    for lang_id, url in TOP_OPEN_SUBTITLES_SENTENCES_SOURCES.items():
        combined[lang_id].append(url)

    for lang_id, url in GOOGLE_BOOKS_SOURCES.items():
        combined[lang_id].append(url)

    return combined


LANGUAGE_NAMES_ENG_AND_NATIVE = {
    "ab": {"name": "Abkhaz", "nativeName": "аҧсуа"},
    "aa": {"name": "Afar", "nativeName": "Afaraf"},
    "af": {"name": "Afrikaans", "nativeName": "Afrikaans"},
    "ak": {"name": "Akan", "nativeName": "Akan"},
    "sq": {"name": "Albanian", "nativeName": "Shqip"},
    "am": {"name": "Amharic", "nativeName": "አማርኛ"},
    "ar": {"name": "Arabic", "nativeName": "العربية"},
    "an": {"name": "Aragonese", "nativeName": "Aragonés"},
    "hy": {"name": "Armenian", "nativeName": "Հայերեն"},
    "as": {"name": "Assamese", "nativeName": "অসমীয়া"},
    "av": {"name": "Avaric", "nativeName": "авар мацӀ, магӀарул мацӀ"},
    "ae": {"name": "Avestan", "nativeName": "avesta"},
    "ay": {"name": "Aymara", "nativeName": "aymar aru"},
    "az": {"name": "Azerbaijani", "nativeName": "azərbaycan dili"},
    "bm": {"name": "Bambara", "nativeName": "bamanankan"},
    "ba": {"name": "Bashkir", "nativeName": "башҡорт теле"},
    "eu": {"name": "Basque", "nativeName": "euskara, euskera"},
    "be": {"name": "Belarusian", "nativeName": "Беларуская"},
    "bn": {"name": "Bengali", "nativeName": "বাংলা"},
    "bh": {"name": "Bihari", "nativeName": "भोजपुरी"},
    "bi": {"name": "Bislama", "nativeName": "Bislama"},
    "bs": {"name": "Bosnian", "nativeName": "bosanski jezik"},
    "br": {"name": "Breton", "nativeName": "brezhoneg"},
    "bg": {"name": "Bulgarian", "nativeName": "български език"},
    "my": {"name": "Burmese", "nativeName": "ဗမာစာ"},
    "ca": {"name": "Catalan; Valencian", "nativeName": "Català"},
    "ch": {"name": "Chamorro", "nativeName": "Chamoru"},
    "ce": {"name": "Chechen", "nativeName": "нохчийн мотт"},
    "ny": {"name": "Chichewa; Chewa; Nyanja", "nativeName": "chiCheŵa, chinyanja"},
    "zh": {"name": "Chinese", "nativeName": "中文 (Zhōngwén), 汉语, 漢語"},
    "cv": {"name": "Chuvash", "nativeName": "чӑваш чӗлхи"},
    "kw": {"name": "Cornish", "nativeName": "Kernewek"},
    "co": {"name": "Corsican", "nativeName": "corsu, lingua corsa"},
    "cr": {"name": "Cree", "nativeName": "ᓀᐦᐃᔭᐍᐏᐣ"},
    "hr": {"name": "Croatian", "nativeName": "hrvatski"},
    "cs": {"name": "Czech", "nativeName": "česky, čeština"},
    "da": {"name": "Danish", "nativeName": "dansk"},
    "dv": {"name": "Divehi; Dhivehi; Maldivian", "nativeName": "ދިވެހި"},
    "nl": {"name": "Dutch", "nativeName": "Nederlands, Vlaams"},
    "en": {"name": "English", "nativeName": "English"},
    "eo": {"name": "Esperanto", "nativeName": "Esperanto"},
    "et": {"name": "Estonian", "nativeName": "eesti, eesti keel"},
    "ee": {"name": "Ewe", "nativeName": "Eʋegbe"},
    "fo": {"name": "Faroese", "nativeName": "føroyskt"},
    "fj": {"name": "Fijian", "nativeName": "vosa Vakaviti"},
    "fi": {"name": "Finnish", "nativeName": "suomi, suomen kieli"},
    "fr": {"name": "French", "nativeName": "français, langue française"},
    "ff": {"name": "Fula; Fulah; Pulaar; Pular", "nativeName": "Fulfulde, Pulaar, Pular"},
    "gl": {"name": "Galician", "nativeName": "Galego"},
    "ka": {"name": "Georgian", "nativeName": "ქართული"},
    "de": {"name": "German", "nativeName": "Deutsch"},
    "el": {"name": "Greek, Modern", "nativeName": "Ελληνικά"},
    "gn": {"name": "Guaraní", "nativeName": "Avañeẽ"},
    "gu": {"name": "Gujarati", "nativeName": "ગુજરાતી"},
    "ht": {"name": "Haitian; Haitian Creole", "nativeName": "Kreyòl ayisyen"},
    "ha": {"name": "Hausa", "nativeName": "Hausa, هَوُسَ"},
    "he": {"name": "Hebrew", "nativeName": "עברית"},
    "hz": {"name": "Herero", "nativeName": "Otjiherero"},
    "hi": {"name": "Hindi", "nativeName": "हिन्दी, हिंदी"},
    "ho": {"name": "Hiri Motu", "nativeName": "Hiri Motu"},
    "hu": {"name": "Hungarian", "nativeName": "Magyar"},
    "ia": {"name": "Interlingua", "nativeName": "Interlingua"},
    "id": {"name": "Indonesian", "nativeName": "Bahasa Indonesia"},
    "ie": {"name": "Interlingue", "nativeName": "Interlingue"},
    "ga": {"name": "Irish", "nativeName": "Gaeilge"},
    "ig": {"name": "Igbo", "nativeName": "Asụsụ Igbo"},
    "ik": {"name": "Inupiaq", "nativeName": "Iñupiaq, Iñupiatun"},
    "io": {"name": "Ido", "nativeName": "Ido"},
    "is": {"name": "Icelandic", "nativeName": "Íslenska"},
    "it": {"name": "Italian", "nativeName": "Italiano"},
    "iu": {"name": "Inuktitut", "nativeName": "ᐃᓄᒃᑎᑐᑦ"},
    "ja": {"name": "Japanese", "nativeName": "日本語 (にほんご／にっぽんご)"},
    "jv": {"name": "Javanese", "nativeName": "basa Jawa"},
    "kl": {"name": "Kalaallisut, Greenlandic", "nativeName": "kalaallisut, kalaallit oqaasii"},
    "kn": {"name": "Kannada", "nativeName": "ಕನ್ನಡ"},
    "kr": {"name": "Kanuri", "nativeName": "Kanuri"},
    "ks": {"name": "Kashmiri", "nativeName": "कश्मीरी, كشميري"},
    "kk": {"name": "Kazakh", "nativeName": "Қазақ тілі"},
    "km": {"name": "Khmer", "nativeName": "ភាសាខ្មែរ"},
    "ki": {"name": "Kikuyu, Gikuyu", "nativeName": "Gĩkũyũ"},
    "rw": {"name": "Kinyarwanda", "nativeName": "Ikinyarwanda"},
    "ky": {"name": "Kirghiz, Kyrgyz", "nativeName": "кыргыз тили"},
    "kv": {"name": "Komi", "nativeName": "коми кыв"},
    "kg": {"name": "Kongo", "nativeName": "KiKongo"},
    "ko": {"name": "Korean", "nativeName": "한국어 (韓國語), 조선말 (朝鮮語)"},
    "ku": {"name": "Kurdish", "nativeName": "Kurdî, كوردی"},
    "kj": {"name": "Kwanyama, Kuanyama", "nativeName": "Kuanyama"},
    "la": {"name": "Latin", "nativeName": "latine, lingua latina"},
    "lb": {"name": "Luxembourgish, Letzeburgesch", "nativeName": "Lëtzebuergesch"},
    "lg": {"name": "Luganda", "nativeName": "Luganda"},
    "li": {"name": "Limburgish, Limburgan, Limburger", "nativeName": "Limburgs"},
    "ln": {"name": "Lingala", "nativeName": "Lingála"},
    "lo": {"name": "Lao", "nativeName": "ພາສາລາວ"},
    "lt": {"name": "Lithuanian", "nativeName": "lietuvių kalba"},
    "lu": {"name": "Luba-Katanga", "nativeName": ""},
    "lv": {"name": "Latvian", "nativeName": "latviešu valoda"},
    "gv": {"name": "Manx", "nativeName": "Gaelg, Gailck"},
    "mk": {"name": "Macedonian", "nativeName": "македонски јазик"},
    "mg": {"name": "Malagasy", "nativeName": "Malagasy fiteny"},
    "ms": {"name": "Malay", "nativeName": "bahasa Melayu, بهاس ملايو"},
    "ml": {"name": "Malayalam", "nativeName": "മലയാളം"},
    "mt": {"name": "Maltese", "nativeName": "Malti"},
    "mi": {"name": "Māori", "nativeName": "te reo Māori"},
    "mr": {"name": "Marathi (Marāṭhī)", "nativeName": "मराठी"},
    "mh": {"name": "Marshallese", "nativeName": "Kajin M̧ajeļ"},
    "mn": {"name": "Mongolian", "nativeName": "монгол"},
    "na": {"name": "Nauru", "nativeName": "Ekakairũ Naoero"},
    "nv": {"name": "Navajo, Navaho", "nativeName": "Diné bizaad, Dinékʼehǰí"},
    "nb": {"name": "Norwegian Bokmål", "nativeName": "Norsk bokmål"},
    "nd": {"name": "North Ndebele", "nativeName": "isiNdebele"},
    "ne": {"name": "Nepali", "nativeName": "नेपाली"},
    "ng": {"name": "Ndonga", "nativeName": "Owambo"},
    "nn": {"name": "Norwegian Nynorsk", "nativeName": "Norsk nynorsk"},
    "no": {"name": "Norwegian", "nativeName": "Norsk"},
    "ii": {"name": "Nuosu", "nativeName": "ꆈꌠ꒿ Nuosuhxop"},
    "nr": {"name": "South Ndebele", "nativeName": "isiNdebele"},
    "oc": {"name": "Occitan", "nativeName": "Occitan"},
    "oj": {"name": "Ojibwe, Ojibwa", "nativeName": "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
    "cu": {"name": "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "nativeName": "ѩзыкъ словѣньскъ"},
    "om": {"name": "Oromo", "nativeName": "Afaan Oromoo"},
    "or": {"name": "Oriya", "nativeName": "ଓଡ଼ିଆ"},
    "os": {"name": "Ossetian, Ossetic", "nativeName": "ирон æвзаг"},
    "pa": {"name": "Panjabi, Punjabi", "nativeName": "ਪੰਜਾਬੀ, پنجابی"},
    "pi": {"name": "Pāli", "nativeName": "पाऴि"},
    "fa": {"name": "Persian", "nativeName": "فارسی"},
    "pl": {"name": "Polish", "nativeName": "polski"},
    "ps": {"name": "Pashto, Pushto", "nativeName": "پښتو"},
    "pt": {"name": "Portuguese", "nativeName": "Português"},
    "qu": {"name": "Quechua", "nativeName": "Runa Simi, Kichwa"},
    "rm": {"name": "Romansh", "nativeName": "rumantsch grischun"},
    "rn": {"name": "Kirundi", "nativeName": "kiRundi"},
    "ro": {"name": "Romanian, Moldavian, Moldovan", "nativeName": "română"},
    "ru": {"name": "Russian", "nativeName": "русский язык"},
    "sa": {"name": "Sanskrit (Saṁskṛta)", "nativeName": "संस्कृतम्"},
    "sc": {"name": "Sardinian", "nativeName": "sardu"},
    "sd": {"name": "Sindhi", "nativeName": "सिन्धी, سنڌي، سندھی"},
    "se": {"name": "Northern Sami", "nativeName": "Davvisámegiella"},
    "sm": {"name": "Samoan", "nativeName": "gagana faa Samoa"},
    "sg": {"name": "Sango", "nativeName": "yângâ tî sängö"},
    "sr": {"name": "Serbian", "nativeName": "српски језик"},
    "gd": {"name": "Scottish Gaelic; Gaelic", "nativeName": "Gàidhlig"},
    "sn": {"name": "Shona", "nativeName": "chiShona"},
    "si": {"name": "Sinhala, Sinhalese", "nativeName": "සිංහල"},
    "sk": {"name": "Slovak", "nativeName": "slovenčina"},
    "sl": {"name": "Slovene", "nativeName": "slovenščina"},
    "so": {"name": "Somali", "nativeName": "Soomaaliga, af Soomaali"},
    "st": {"name": "Southern Sotho", "nativeName": "Sesotho"},
    "es": {"name": "Spanish; Castilian", "nativeName": "español, castellano"},
    "su": {"name": "Sundanese", "nativeName": "Basa Sunda"},
    "sw": {"name": "Swahili", "nativeName": "Kiswahili"},
    "ss": {"name": "Swati", "nativeName": "SiSwati"},
    "sv": {"name": "Swedish", "nativeName": "svenska"},
    "ta": {"name": "Tamil", "nativeName": "தமிழ்"},
    "te": {"name": "Telugu", "nativeName": "తెలుగు"},
    "tg": {"name": "Tajik", "nativeName": "тоҷикӣ, toğikī, تاجیکی"},
    "th": {"name": "Thai", "nativeName": "ไทย"},
    "ti": {"name": "Tigrinya", "nativeName": "ትግርኛ"},
    "bo": {"name": "Tibetan Standard, Tibetan, Central", "nativeName": "བོད་ཡིག"},
    "tk": {"name": "Turkmen", "nativeName": "Türkmen, Түркмен"},
    "tl": {"name": "Tagalog", "nativeName": "Wikang Tagalog"},
    "tn": {"name": "Tswana", "nativeName": "Setswana"},
    "to": {"name": "Tonga (Tonga Islands)", "nativeName": "faka Tonga"},
    "tr": {"name": "Turkish", "nativeName": "Türkçe"},
    "ts": {"name": "Tsonga", "nativeName": "Xitsonga"},
    "tt": {"name": "Tatar", "nativeName": "татарча, tatarça, تاتارچا"},
    "tw": {"name": "Twi", "nativeName": "Twi"},
    "ty": {"name": "Tahitian", "nativeName": "Reo Tahiti"},
    "ug": {"name": "Uighur, Uyghur", "nativeName": "Uyƣurqə, ئۇيغۇرچە"},
    "uk": {"name": "Ukrainian", "nativeName": "українська"},
    "ur": {"name": "Urdu", "nativeName": "اردو"},
    "uz": {"name": "Uzbek", "nativeName": "zbek, Ўзбек, أۇزبېك"},
    "ve": {"name": "Venda", "nativeName": "Tshivenḓa"},
    "vi": {"name": "Vietnamese", "nativeName": "Tiếng Việt"},
    "vo": {"name": "Volapük", "nativeName": "Volapük"},
    "wa": {"name": "Walloon", "nativeName": "Walon"},
    "cy": {"name": "Welsh", "nativeName": "Cymraeg"},
    "wo": {"name": "Wolof", "nativeName": "Wollof"},
    "fy": {"name": "Western Frisian", "nativeName": "Frysk"},
    "xh": {"name": "Xhosa", "nativeName": "isiXhosa"},
    "yi": {"name": "Yiddish", "nativeName": "ייִדיש"},
    "yo": {"name": "Yoruba", "nativeName": "Yorùbá"},
    "za": {"name": "Zhuang, Chuang", "nativeName": "Saɯ cueŋƅ, Saw cuengh"}
}

NAMES_FOR_THE_ENGLISH_LANGUAGE = {
    "English",
    "Inglés",
    "Anglais",
    "Englisch",
    "Inglese",
    "Inglês",
    "영어",
    "英語",
    "英语",
    "Angielski",
    "Engleski",
    "Engleză",
    "Английский",
    "Engelsk",
    "Englanti",
    "Inglise",
    "Αγγλικά",
    "Ingiliz",
    "Ingilizce",
    "Englis",
    "إنجليزي",
    "Инглиш",
    "Inglizcha",
    "Ingliz tili",
    "İngliz tili",
    "Engels",
    "Anglický",
    "Englesko",
    "Anglický jazyk",
    "Inglês",
    "Angli",
    "Englanti",
    "An Bèarla",
    "Engles",
    "Engelisi",
    "Inglis",
    "Englannin kieli",
    "İngilizce",
    "Англійська",
    "Английска",
    "Angličtina",
    "An Bhéarla",
    "Ingles",
    "Anglit",
    "Engelska",
    "Inglese",
    "Anglicky",
    "Angli",
    "Angļu",
    "Engels",
    "Anglų",
    "Engel",
    "Engils",
    "Angličina",
    "Angol",
    "Angļu valoda",
    "Inglise keel",
    "Ingiriisi",
    "Ingilisi",
    "Englysch",
    "Inglis",
    "Angliškai",
    "Engleză",
    "Engilsz",
    "Englez",
    "Anglicko",
    "Angolul",
    "Engelska",
    "Inglés",
    "Englezski",
    "Englezki",
    "Englis",
    "العربية",
    "英文",
    "英语",
    "eigo",
    "yeong-eo",
    "Inglẽs",
    "Англиiskий",
    "ภาษาอังกฤษ",
    "tiếng Anh",
    "Angolano",
    "Англиски",
    "Englesh",
    "Αγγλική",
    "Angol",
    "Inggris",
    "Inglés",
    "אנגלית",
    "Anglijan",
    "İngiliscə",
    "Англиски",
    "Англиски",
    "Английски",
    "Англиски",
    "Англиски",
}
